import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {SKILL_BY_ID} from '../shared/data/skills.js';
const context=vm.createContext({Math,Phaser:{BlendModes:{ADD:1}}});
const source=readFileSync(new URL('../client/js/topdown/TdSkills.js',import.meta.url),'utf8');
const imports=new Map([...source.matchAll(/import \{([^}]+)\} from '([^']+)'/g)].map(m=>[m[2],m[1].split(',').map(s=>s.trim())]));
const mod=new vm.SourceTextModule(source,{context});
await mod.link(spec=>{const names=imports.get(spec);return new vm.SyntheticModule(names,function(){for(const n of names)this.setExport(n,n==='HEAL_TINT'?{}:undefined);},{context});});
await mod.evaluate();
const rectangles=[],tweens=[];
const scene={settings:{fxFlash:'off'},cameras:{main:{width:960,height:540,zoom:2,worldView:{centerX:5000,centerY:6000}}},add:{rectangle(x,y,w,h,color,alpha){const r={x,y,w,h,color,alpha,setScrollFactor(v){this.scroll=v;return this;},setDepth(v){this.depth=v;return this;},setBlendMode(){return this;},destroy(){}};rectangles.push(r);return r;}},tweens:{add(t){tweens.push(t);}}};
const fx=new mod.namespace.GrandFx(scene);
fx.flash();fx.darken();assert.equal(rectangles.length,0,'disabled flash preference remains effective');
scene.settings.fxFlash='soft';fx.flash();fx.darken();
assert.deepEqual(rectangles.map(r=>[r.x,r.y,r.w,r.h,r.scroll]),[[240,135,520,310,0],[240,135,520,310,0]],'screen effects cover the viewport independently of map position and zoom');
assert.ok(Math.abs(rectangles[0].alpha-.165)<1e-9,'soft flash retains reduced intensity');
const active=Object.values(SKILL_BY_ID).filter(s=>s.type!=='passive'),passive=Object.values(SKILL_BY_ID).filter(s=>s.type==='passive');
assert.equal(active.length,55);assert.equal(passive.length,10);
for(const sk of active)assert.ok(source.includes(sk.id)||readFileSync(new URL('../client/js/topdown/TdHealer.js',import.meta.url),'utf8').includes(sk.id),'active skill has an authored effect entry: '+sk.id);
console.log('Screen effect coverage/preferences and 55 active / 10 passive skill catalogue passed.');
